<div class="uk-section uk-section-default uk-preserve-color uk-padding-remove">
    <div class="uk-container uk-container-expand">
        <div uk-grid>
            <div class="uk-width-1-2@m">
    	        <h1>院内商品詳細</h1>
            </div>
            <div class="uk-width-1-2@m uk-text-right">
                <form action="<?php echo $form_url ?>" method="post">
                    <input type="hidden" name="priceId" value="%val:usr:priceId%">
                    <button class="uk-button uk-button-primary" type="submit" value="update" name="Action">院内商品情報変更</button>
                </form>
            </div>
        </div>
        <table class="uk-table uk-table-divider">
            <tbody>
                <tr>
                    <th>
                        不使用フラグ
                    </th>
                    <td>
                        %val:usr:notUsedFlag:v%
                    </td>
                </tr>
                <tr>
                    <th>
                        登録日時
                    </th>
                    <td>
                        %val:usr:registrationTime%
                    </td>
                </tr>
                <tr>
                    <th>
                        更新日時
                    </th>
                    <td>
                        %val:usr:updateTime%
                    </td>
                </tr>
                <tr>
                    <th>
                        院内商品ID
                    </th>
                    <td>
                        %val:usr:inHospitalItemId%
                    </td>
                </tr>
                <tr>
                    <th>
                        病院名
                    </th>
                    <td>
                        %val:usr:hospitalName%
                    </td>
                </tr>
                <tr>
                    <th>
                        病院Id
                    </th>
                    <td>
                        %val:usr:hospitalId%
                    </td>
                </tr>
                <tr>
                    <th>
                        卸業者名
                    </th>
                    <td>
                        %val:usr:distributorName%
                    </td>
                </tr>
                <tr>
                    <th>
                        卸業者Id
                    </th>
                    <td>
                        %val:usr:distributorId%
                    </td>
                </tr>
                <tr>
                    <th>
                        共通ID
                    </th>
                    <td>
                        %val:usr:distCommonId%
                    </td>
                </tr>
                <tr>
                    <th>
                        メーカー名
                    </th>
                    <td>
                        %val:usr:makerName%
                    </td>
                </tr>
                <tr>
                    <th>
                        商品名
                    </th>
                    <td>
                        %val:usr:itemName%
                    </td>
                </tr>
                <tr>
                    <th>
                        製品コード
                    </th>
                    <td>
                        %val:usr:itemCode%
                    </td>
                </tr>
                <tr>
                    <th>
                        規格
                    </th>
                    <td>
                        %val:usr:itemStandard%
                    </td>
                </tr>
                <tr>
                    <th>
                        JANコード
                    </th>
                    <td>
                        %val:usr:itemJANCode%
                    </td>
                </tr>
                <tr>
                    <th>
                        分類
                    </th>
                    <td>
                        %val:usr:category%
                    </td>
                </tr>
                <tr>
                    <th>
                        カタログNo
                    </th>
                    <td>
                        %val:usr:catalogNo%
                    </td>
                </tr>
                <tr>
                    <th>
                        シリアルNo
                    </th>
                    <td>
                        %val:usr:serialNo%
                    </td>
                </tr>
                <tr>
                    <th>
                        入数
                    </th>
                    <td>
                        %val:usr:quantity%
                    </td>
                </tr>
                <tr>
                    <th>
                        入数単位
                    </th>
                    <td>
                        %val:usr:quantityUnit%
                    </td>
                </tr>
                <tr>
                    <th>
                        個数単位
                    </th>
                    <td>
                        %val:usr:itemUnit%
                    </td>
                </tr>
                <tr>
                    <th>
                        保険請求分類（医科）
                    </th>
                    <td>
                        %val:usr:medicineCategory:br%
                    </td>
                </tr>
                <tr>
                    <th>
                        保険請求分類（在宅）
                    </th>
                    <td>
                        %val:usr:homeCategory:br%
                    </td>
                </tr>
                <tr>
                    <th>
                        特記事項
                    </th>
                    <td>
                        %val:usr:notice:br%
                    </td>
                </tr>
                <tr>
                    <th>
                        院内総在庫数
                    </th>
                    <td>
                        %val:usr:HPstock%
                    </td>
                </tr>
                <tr>
                    <th>
                        価格
                    </th>
                    <td>
                        %val:usr:price%
                    </td>
                </tr>
                <tr>
                    <th>
                        旧価格
                    </th>
                    <td>
                        %val:usr:oldPrice%
                    </td>
                </tr>
                <tr>
                    <th>
                        ラベルID
                    </th>
                    <td>
                        %val:usr:labelId%
                    </td>
                </tr>
                <tr>
                    <th>
                        定価
                    </th>
                    <td>
                        %val:usr:minPrice%
                    </td>
                </tr>
                <tr>
                    <th>
                        単価
                    </th>
                    <td>
                        %val:usr:unitPrice%
                    </td>
                </tr>
                <tr>
                    <th>
                        測定機器名
                    </th>
                    <td>
                        %val:usr:measuringInst%
                    </td>
                </tr>
                <tr>
                    <th>
                        償還価格フラグ
                    </th>
                    <td>
                        %val:usr:officialFlag:v%
                    </td>
                </tr>
                <tr>
                    <th>
                        償還価格
                    </th>
                    <td>
                        %val:usr:officialprice%
                    </td>
                </tr>
                <tr>
                    <th>
                        ロット管理フラグ
                    </th>
                    <td>
                        %val:usr:lotManagement:v%
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr></tr>
            </tfoot>
        </table>
    </div>
</div>
